### ISSUE TITLE
gulp error after npm start

### ISSUE THREAD

**Issue by ahakem** [xiaolin/react-image-gallery#495]
`➜  react-image-gallery git:(master) ✗ npm start

> react-image-gallery@1.0.6 start /Users/hakim/usytech/react-image-gallery
> gulp dev

assert.js:385
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/hakim/usytech/react-image-gallery/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/hakim/usytech/react-image-gallery/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/hakim/usytech/react-image-gallery/gulpfile.js:90:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at execute (/Users/hakim/usytech/react-image-gallery/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-image-gallery@1.0.6 start: `gulp dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-image-gallery@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2020-03-16T19_16_30_204Z-debug.log
`

**Comment by ahakem** [comment]
this fixed by downgrading node to v 10
