### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by pm0u** [xiaolin/react-image-gallery#609]
to reproduce:

clone the repo
checkout tag v1.1.0
run `yarn start`

```
$ yarn start
yarn run v1.22.10
$ gulp dev
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/home/paul/Git/react-image-gallery/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/paul/Git/react-image-gallery/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/paul/Git/react-image-gallery/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

node v 14.16.0

**Comment by pm0u** [comment]
nevermind, i see now that you need to use < node v11
