### ISSUE TITLE
Missing key step in example instructions

### ISSUE THREAD

**Issue by JamesTheBald** [xiaolin/react-image-gallery#657]
**Describe the bug**

The instructions for how to install and run the example of this package are missing a key step: you have to install webpack before attempting to run it. The example crashes upon running without webpack installed. This can trip up new devs like me.

**Image Gallery Version**
What version of `react-image-gallery` are you using?
1.2.7

**To Reproduce**
Follow the instructions for "Build the example locally", at the bottom of the main repo, on a computer that doesn't have webpack installed. (I'm a junior dev, so I didn't have this installed yet.)

**Expected behavior**
If webpack is not installed, running "yarn start" from the command line causes a compiler crash

**Screenshots**
Here's the page of alarming jibberish I saw when the compiler crashed:

_### **### Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:934:10)
    at /Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:743:11)
    at /Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:807:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:934:10)
    at /Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:743:11)
    at /Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:807:5
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:934:10)
    at /Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:743:11)
    at /Users/jimbo/0Code/react-image-gallery/react-image-gallery/node_modules/webpack/lib/NormalModule.js:807:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.**_

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Mac 12.0.1 Monterey
 - Browser [e.g. chrome, safari]  Chrome 
 - Version [e.g. 22]  98.0.4758

**Comment by ethananselkelly** [comment]
Hi, wasn't able to recreate this issue. Webpack was listed in the devDependencies. I think we can close this issue.
