### ISSUE TITLE
I'm getting a type error suddenly

### ISSUE THREAD

**Issue by DevenRathod2** [xiaolin/react-image-gallery#754]
Uncaught TypeError: Super expression must either be null or a function
    at image-gallery.js:1020:1
    at image-gallery.js:1019:1
    at image-gallery.js:1018:1
    at image-gallery.js:314:1
    at Object.<anonymous> (image-gallery.js:4:1)
    at Object.<anonymous> (image-gallery.js:4:1)
    at s (3?item=%7B%22industry%22%3A%22Standard%22%2C%22category%22%3A%2220ft%22%2C%22type%22%3A%222+DR%22%2C%22description%22%3A%2240FT+Container+111%22%2C%22assetNo%22%3A%22Container%22%2C%22location%22%3A%22TX+Del+Rio+78840%22%2C%22model%22%3A%22KS11%22%2C%22manufacturer%22%3A%22KingSurplus%22%7D:1:2690)
    at Module.<anonymous> (Inventory.js:63:14)
    at s (3?item=%7B%22industry%22%3A%22Standard%22%2C%22category%22%3A%2220ft%22%2C%22type%22%3A%222+DR%22%2C%22description%22%3A%2240FT+Container+111%22%2C%22assetNo%22%3A%22Container%22%2C%22location%22%3A%22TX+Del+Rio+78840%22%2C%22model%22%3A%22KS11%22%2C%22manufacturer%22%3A%22KingSurplus%22%7D:1:2690)
    at Object.<anonymous> (logo.webp:1:41)

I'm getting this error suddenly i wonder why its happing please help me to fix this

**Comment by xiaolin** [comment]
This is not an issue with this lib. Please check your transpiler and settings and look at previously close issue which may help.
See https://github.com/xiaolin/react-image-gallery/issues/624

**Comment by DevenRathod2** [comment]
I'm not using webpack in my react app is their any other solution to get it fix?

**Comment by xiaolin** [comment]
If you list steps to reproduce the error, I can take a look.

**Comment by DevenRathod2** [comment]
it happens suddenly here is the code where i'm using `react-image-gallery`
please help i need to get it done today somehow

```
import React, { useEffect, useState } from "react";
import ImageGallery from "react-image-gallery";
import {
  Col,
  Container,
  Image,
  Row,
  Spinner,
  Button,
  Breadcrumb,
} from "react-bootstrap";
import { Icon } from "@iconify/react";
i

function InventoryDetail() {
  useDocumentTitle("PC | Inv. Detail");
  const { id } = useParams();

  const dispatch = useDispatch();
  const navigate = useNavigate();
  const location = useLocation();

  const [data, setData] = useState({});
  const [gallery, setGallery] = useState({});
  const [relatedItems, setRelatedItems] = useState({});

  const userData = JSON.parse(localStorage.getItem("login"));
  const [loading, setLoading] = useState(false);
  const [show, setshow] = useState(false);
  const [showLater, setshowLater] = useState(false);
  const [showLogin, setShowLogin] = useState(null);
  const [isBuyNow, setIsBuyNow] = useState(false);

  const handleshow = () => {
    if (show == false) {
      if (show == false) {
        setshow(true);
      }
    } else {
      setshow(!show);
    }
  };
  const handleShowLogin = () => {
    if (showLogin == null) {
      if (showLogin == null) {
        setShowLogin(true);
      }
    } else {
      setShowLogin(!showLogin);
    }
  };

  useEffect(() => {
    const getItemById = async () => {
      try {
        const res = await axiosClient.get("GetItemById/" + Number(id));
        if (res.qbRecordId) {
          const imgList = await axiosClient.get(
            "GetItemImageGallery/" + Number(res.qbRecordId)
          );
          const sortedImgData = imgList.sort(compare);
          setGallery({ data: sortedImgData });
        }
        if (res.relatedCategoryId) {
          const relatedData = await axiosClient.get(
            "GetRandomItemByCategory/" + Number(res.relatedCategoryId)
          );
          setRelatedItems({ data: relatedData });
        }
        setData({ item: res });
      } catch (error) {
        console.log(error);
      }
    };
    getItemById();
  }, []);
  function compare(a, b) {
    if (a.sortOrder < b.sortOrder) {
      return -1;
    } else if (a.sortOrder > b.sortOrder) {
      return 1;
    } else {
      return 0;
    }
  }
  function addCart(selectedItem) {
    var loginData = JSON.parse(localStorage.getItem("login"));
    if (loginData == null) {
      setIsBuyNow(false);
      handleShowLogin();
    } else {
      dispatch(handleAddCart(selectedItem));
      dispatch(getTotals());
      toast.success("Container Added to Cart");
    }
  }
  function buyNow(selectedItem) {
    var loginData = JSON.parse(localStorage.getItem("login"));
    if (loginData == null) {
      setIsBuyNow(true);
      handleShowLogin();
    } else {
      dispatch(handleAddCart(selectedItem));
      dispatch(getTotals());
      navigate("/ShoppingCart");
    }
  }
  async function saveLaterItem(selectedItem) {
    setLoading(true);
    var loginData = JSON.parse(localStorage.getItem("login"));
    if (loginData == null) {
      navigate("/login");
    } else {
      try {
        var body = {
          id: 0,
          userId: userData.user.id,
          ItemId: Number(selectedItem.id),
        };
        await axiosClient.post("saveSaveLaterInfo", body).then((res) => {
          setLoading(false);
          setshowLater(true);
          toast.success("Successfully saved for later");
        });
      } catch (error) {
        setLoading(false);
      }
    }
  }

  const gotToInventoryByIndustry = (item) => {
    var selectItem = {
      id: item.relatedIndustrId,
      name: item.industryName,
    };
    dispatch(setIndustry(selectItem));
    navigate("/Containers", { state: { industryId: item.id } });
  };

  return (
    <>
      <Header />

      {data && data.item && (
        <div className="d-margin">
          <SeoHelmet
            title="PC | Inv. Details"
            description={data.item.title}
            name="Pro Container"
            type="website"
            canonical={data.item.title}
            url={window.location.href}
          />

          <Helmet>
            <meta name="manufacturer" content={data.item.menufacturer} />
            <meta name="model" content={data.item.model} />
            <meta name="asset-number" content={data.item.assetNumber} />
            <meta name="hp-amp-kw-kva" content={data.item.hP_AMP_KW_KVA} />
            <meta name="voltage" content={data.item.voltage} />
            <meta name="length-inches" content={data.item.lengthInches} />
            <meta
              name="packaging-weight"
              content={data.item.estiamtedPackaginWeight}
            />
            <meta name="year" content={data.item.year} />
            <meta name="amps" content={data.item.amps} />
            <meta name="phase" content={data.item.phase} />
            <meta name="width-inches" content={data.item.widthInches} />
            <meta name="height-inches" content={data.item.heightInches} />
            <meta name="weight-lbs" content={data.item.weightLBS} />
          </Helmet>

          <Container>
            <Link className="backBTn" to="/Containers">
              <Icon icon="material-symbols:arrow-back-ios-new-rounded" /> Back
            </Link>
            <Breadcrumb className="pt-4">
              {data.item.industryName && (
                <Breadcrumb.Item
                  onClick={() => {
                    gotToInventoryByIndustry(data.item);
                  }}
                >
                  {data.item.industryName}
                </Breadcrumb.Item>
              )}

              {data.item.categoryName && (
                <Breadcrumb.Item
                  onClick={() => {
                    gotToInventoryByCategory(data.item);
                  }}
                >
                  {data.item.categoryName}
                </Breadcrumb.Item>
              )}
              {data.item.typeName && (
                <Breadcrumb.Item
                  onClick={() => {
                    gotToInventoryByType(data.item);
                  }}
                >
                  {data.item.typeName}
                </Breadcrumb.Item>
              )}
            </Breadcrumb>
            <Row>
              <Col lg={6}>
                <div className="SliderImage">{setSlider()}</div>
              </Col>
              {itemDescription()}
            </Row>
            {inspectionReport()}
            <div className="similar-product">
              {relatedItems &&
                relatedItems.data &&
                relatedItems.data.length > 0 && (
                  <>
                    <h4>Similar Items Nearby</h4>
                    <Row>
                      {relatedItems.data.map((product) => (
                        <Col key={product.id} xl={3} lg={4} md={6}>
                          <ProductCard RecentProductList={product} />
                        </Col>
                      ))}
                    </Row>
                  </>
                )}
            </div>
          </Container>
        </div>
      )}
      <Footer />
    </>
  );

  function setSlider() {
    if (gallery && gallery.data && gallery.data.length > 0) {
      return (
        <div className="product-gallery-img">
          <ImageGallery items={gallery.data} />

          {/* <div className="RentTag">
            {data.item.isRental == true && (
              <a className="rentTa">Available For Rent</a>
            )}
          </div> */}
          <ul className="product-share-icons">
            <li>
              <Link to="/">
                <Icon icon="fluent:print-20-filled" />
              </Link>
            </li>
            <li>
              <Link to="/">
                <Icon icon="fluent:mail-16-filled" />
              </Link>
            </li>
            <li>
              <Link to="/">
                <Icon icon="ant-design:twitter-outlined" />
              </Link>
            </li>
            <li>
              <Link to="/">
                <Icon icon="bxl:facebook-circle" />
              </Link>
            </li>
          </ul>
        </div>
      );
    } else {
      return <Image src="./assets/images/not-found.png" />;
    }
  }

  function itemDescription() {
    if (data && data.item) {
      return (
        <Col lg={6}>
          <div className="product-gallery-info">
            <h3>{data.item.title}</h3>
            <h4>Basic Information</h4>
            <Row>
              <Col lg={6}>
                <h5 className="">
                  Asset # : <span>{data.item.assetNumber}</span>{" "}
                </h5>
              </Col>
              <Col lg={6}>
                <h5 className="">
                  SKU : <span>{data.item.sku} </span>{" "}
                </h5>
              </Col>
            </Row>
            <div className="qty-wrap">
              <h5>
                {" "}
                Available Qty: <span>{data.item.quantity}</span>
              </h5>
            </div>
            <div className="qty-wrap">
              <h5>
                Available on Rent:{" "}
                <span>{data.item.isRental ? "Yes" : "No"}</span>
              </h5>
            </div>
            <h5 className="">
              Inspections - Yellow Tag :{" "}
              <span> {data.item.guaranteeOrAsis && data.item.condition} </span>
            </h5>
            <h5>
              Guarantee or ASIS :{" "}
              <span>
                {data.item.guaranteeOrAsis && data.item.guaranteeOrAsis}
              </span>{" "}
            </h5>
            <h4>Payment Details</h4>
            <Row className="mb-3">
              <Col lg={12}>
                <h5>
                  Appraised Value: <span>${data.item.salePrice} </span>{" "}
                </h5>
              </Col>
              {/* <Col lg={6}> */}
              {/* <h5 className=""> */}
              {/* Delivery/Shipping Cost :{" "} */}
              {/* {data.item.packagingCostData && (
                    <span>{data.item.packagingCostData}</span> // TODO : add pop us to get shipping cost
                  )} */}
              {/* <Button onClick={handleshow}>Get Shipping Cost</Button> */}
              {/* </h5> */}
              {/* </Col> */}
              {/* <Col lg={6}>
                <h5>
                  New Replacement Cost:{" "}
                  <span> ${data.item.newReplacementCostId}</span>
                </h5>
              </Col> */}
              {/* <Col lg={6}>{acceptPaymentfun()}</Col> */}
            </Row>
            <div className="btns-wrap btns-33Wrap">
              <a
                type="button"
                onClick={() => addCart(data.item)}
                className="btn btn-blue btns-33"
              >
                Add To Cart
              </a>
              <a
                type="button"
                onClick={() => buyNow(data.item)}
                className="btn btn-blue btns-33"
              >
                Buy Now
              </a>
              {/* <a
                onClick={handleshow}
                type="button"
                className="btn btn-blue btns-33"
              >
                Make an offer
              </a> */}
              <div className="max-save btns-33">
                {loading ? (
                  <Button
                    className="btn btn-blue w-100 btn-block  mt-3"
                    disabled
                    style={{ position: "relative" }}
                  >
                    <Spinner
                      as="span"
                      animation="border"
                      size="sm"
                      role="status"
                      aria-hidden="true"
                      style={{
                        color: "white",
                        top: "calc(50% - 12px)",
                        left: "calc(50% - 12px)",
                      }}
                    />
                  </Button>
                ) : (
                  <Button
                    className="btn btn-blue w-100 btn-block  mt-3"
                    type="button"
                    onClick={() => saveLaterItem(data.item)}
                  >
                    Save for later
                  </Button>
                )}
              </div>
              <a
                href="tel:830-995-5000"
                className="btn btn-blue btn-icon btns-33"
              >
                <Icon icon="fluent:call-12-filled" className="me-2" />
                Call Us
              </a>
              <a
                href={
                  "mailto:sales@procontainers.com?subject=" +
                  data.item.title +
                  " - " +
                  data.item.assetNumber
                }
                className="btn btn-blue btn-icon btns-33"
              >
                <Icon icon="ic:round-email" className="me-2" />
                Email Us
              </a>
            </div>
          </div>
        </Col>
      );
    }

    function acceptPaymentfun() {
      let acc = data.item.paymentAccept.replace("]", "");
      acc = acc.replace("[", "");
      acc = acc.replace("]", "");
      acc = acc.replace(/"/g, " ");

      return (
        <>
          <h5>Payment Types Accepted : {acc && <span> {acc}</span>}</h5>
        </>
      );
    }
  }

  function N_AIfNull(val) {
    if (
      val == null ||
      val.toString() == "" ||
      val.toString() == "0" ||
      val.toString() == "[]" ||
      val == undefined
    ) {
      return <p>N/A</p>;
    } else {
      return <p>{val}</p>;
    }
  }
  function inspectionReport() {
    if (data && data.item) {
      return (
        <div className="inspection-info">
          <Row>
            <Col lg={12}>
              <div className="bg-white">
                <h3>INSPECTION REPORT</h3>
              </div>
            </Col>
            <Col lg={12}>
              <div className="bg-white report-info">
                <h5>Specifications</h5>
                <Row>
                  <Col lg={6}>
                    <div className="report-detail-item report-detail-Header">
                      <h6>DESCRIPTION</h6>
                      <h6>DETAILS</h6>
                    </div>
                    <div className="report-detail-item">
                      <p>Manufacturer : </p>
                      <p>{N_AIfNull(data.item.menufacturer)}</p>
                    </div>
                    <div className="report-detail-item">
                      <p>Serial #: </p>
                      <p>{N_AIfNull(data.item.serialNo)}</p>
                    </div>
                    {/* <div className="report-detail-item">
                      <p>HP / AMP / KW / KVA : </p>
                      <p>{N_AIfNull(data.item.hP_AMP_KW_KVA)}</p>
                    </div> */}
                    {/* <div className="report-detail-item">
                      <p>Voltage : </p>
                      <p>
                        {(() => {
                          let arr = JSON.parse(data.item.voltage);
                          if (arr && arr[0] == "N/A") {
                            return (
                              <>
                                <p>N/A</p>
                              </>
                            );
                          } else {
                            if (data.item.voltage != null) {
                              let v = data.item.voltage.replace("]", "");
                              v = v.replace("[", "");
                              v = v.replace(/"/g, " ");
                              if (v != null) {
                                return <>{v}</>;
                              }
                            }
                          }
                        })()}
                      </p>
                    </div> */}
                    <div className="report-detail-item">
                      <p>Length (Inches): </p>
                      <p>{N_AIfNull(data.item.lengthInches)}</p>
                    </div>
                    {/* <div className="report-detail-item">
                      <p>Estimated Packaging Weight: </p>
                      <p>{N_AIfNull(data.item.estiamtedPackaginWeight)}</p>
                    </div> */}
                    {/* <div className="report-detail-item">
                      {(() => {
                        let url = "";
                        if (
                          data.item.manuFacturers_Specs &&
                          data.item.manuFacturers_Specs != null
                        ) {
                          const jsonObject = JSON.parse(
                            data.item.manuFacturers_Specs
                          );
                          url = jsonObject.url;
                        }
                        if (url && url != "" && url != null) {
                          return (
                            <>
                              <p>Manufacturers Specs: </p>
                              <button
                                className="btn btn-blue"
                                onClick={(e) => {
                                  e.preventDefault();
                                  getPdfAttachementQB(url);
                                }}
                              >
                                Open Manufacturers Specs
                              </button>
                            </>
                          );
                        } else {
                          return (
                            <>
                              <p>Manufacturers Specs: </p>
                              <p>No Manufacturer Specifications Available</p>
                            </>
                          );
                        }
                      })()}
                    </div> */}
                    <div className="report-detail-item">
                      <p>Estimated Total Weight: </p>
                      <p>{N_AIfNull(data.item.estimatedTotalWeight)}</p>
                    </div>
                  </Col>
                  <Col lg={6}>
                    <div className="report-detail-item report-detail-item2 report-detail-Header">
                      <h6>DESCRIPTION</h6>
                      <h6>DETAILS</h6>
                    </div>
                    <div className="report-detail-item">
                      <p>Model : </p>
                      <p>{N_AIfNull(data.item.model)}</p>
                    </div>
                    <div className="report-detail-item">
                      <p>Year : </p>
                      <p>{N_AIfNull(data.item.year)}</p>
                    </div>
                    {/* <div className="report-detail-item">
                      <p>Amps : </p>
                      <p>{N_AIfNull(data.item.amps)}</p>
                    </div> */}
                    {/* <div className="report-detail-item">
                      <p>Phase : </p>
                      <p>{N_AIfNull(data.item.phase)}</p>
                    </div> */}
                    <div className="report-detail-item">
                      <p>Width (Inches): </p>
                      <p>{N_AIfNull(data.item.widthInches)}</p>
                    </div>
                    <div className="report-detail-item">
                      <p>Height (Inches): </p>
                      <p>{N_AIfNull(data.item.heightInches)}</p>
                    </div>
                  </Col>
                </Row>
              </div>
            </Col>
            {data.item.background != "" && data.item.background != null && (
              <Col lg={12}>
                <div className="bg-white report-info report-info2">
                  <h5>Background</h5>
                  <Row>
                    <Col lg={12}>
                      <div className="report-detail-item">
                        <p
                          dangerouslySetInnerHTML={{
                            __html: data.item.background,
                          }}
                        />
                      </div>
                    </Col>
                  </Row>
                </div>
              </Col>
            )}
            {data.item.factoryInformationOnly != null &&
              data.item.factoryInformationOnly != "" && (
                <Col lg={12}>
                  <div className="bg-white report-info report-info2">
                    <h5>Factory Information</h5>
                    <Row>
                      <Col lg={12}>
                        <div className="report-detail-item">
                          <p
                            dangerouslySetInnerHTML={{
                              __html: data.item.factoryInformationOnly,
                            }}
                          />
                        </div>
                      </Col>
                    </Row>
                  </div>
                </Col>
              )}
          </Row>
          {show != null && <MakeOffer item={data.item} show={show} />}

          <LoginModal item={data.item} show={showLogin} isBuyNow={isBuyNow} />
          {/* <GetShippingCost /> */}
        </div>
      );
    }
  }

  function getPdfAttachementQB(url) {
    axios
      .get(`https://api.quickbase.com/v1${url}`, appConstants.config)
      .then((response) => {
        const byteCharacters = atob(response.data);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        const blob = new Blob([byteArray], { type: "application/pdf" });
        const url = URL.createObjectURL(blob);
        window.open(url, "_blank");
      })
      .catch((error) => {
        console.log(error);
      });
  }
}

export default InventoryDetail;

```

`package.json`

```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@react-google-maps/api": "^2.18.1",
    "@reduxjs/toolkit": "^1.9.1",
    "@stripe/react-stripe-js": "^1.16.1",
    "@stripe/stripe-js": "^1.46.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "axios": "^1.4.0",
    "bootstrap": "^5.2.2",
    "jquery": "^3.6.1",
    "lodash": "^4.17.21",
    "npm-check": "^6.0.1",
    "react": "^18.2.0",
    "react-bootstrap": "^2.5.0",
    "react-countup": "^6.3.2",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0",
    "react-helmet-async": "^1.3.0",
    "react-image-gallery": "^1.2.11",
    "react-query": "^3.39.3",
    "react-redux": "^8.0.5",
    "react-router": "^6.11.0",
    "react-scripts": "^2.1.3",
    "react-select": "^5.7.0",
    "react-slick": "^0.29.0",
    "react-toastify": "^9.1.2",
    "react-uuid": "^2.0.0",
    "redux": "^4.2.0",
    "slick-carousel": "^1.8.1",
    "source-map-explorer": "^2.5.3",
    "sweetalert2": "^11.7.20",
    "web-vitals": "^2.1.4",
    "xml-js": "^1.6.11",
    "xml2js": "^0.5.0"
  },
  "scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@iconify/react": "^4.0.0",
    "react-router-dom": "^6.11.0"
  }
}

```

**Comment by xiaolin** [comment]
can you try upgrading `react-image-gallery: 1.2.11` to `react-image-gallery: 1.3.0` and see if that helps?

**Comment by DevenRathod2** [comment]
did it but nothing works

**Comment by xiaolin** [comment]
Can you try isolating the package and seeing if that still breaks? For example, can you create a new component to test the gallery alone?

```
import React from "react";
import ImageGallery from "react-image-gallery";

const images = [
  {
    original: "https://picsum.photos/id/1018/1000/600/",
    thumbnail: "https://picsum.photos/id/1018/250/150/",
  },
  {
    original: "https://picsum.photos/id/1015/1000/600/",
    thumbnail: "https://picsum.photos/id/1015/250/150/",
  },
  {
    original: "https://picsum.photos/id/1019/1000/600/",
    thumbnail: "https://picsum.photos/id/1019/250/150/",
  },
];

function GalleryTest() {
  return <ImageGallery items={images} />;
}

export default GalleryTest;
```

**Comment by DevenRathod2** [comment]
No not working. only working locally not after build

**Comment by xiaolin** [comment]
What framework are you using to build your app? What version is it?

**Comment by DevenRathod2** [comment]
i'm using ReactJS v18.2.0

**Comment by xiaolin** [comment]
I tried to reproduced with CRA and I was not able to replicate after building it.

1. `npx create-react-app my-app`
2. `cd my-app`
3. `npm start`
4. Add Image gallery component to app.js
5. build production `npm run build`
6. serve the build `serve -s build`

Is it possible you have an older release of CRA maybe? I saw this issue here that may be related to what you're experiencing
https://github.com/facebook/create-react-app/issues/7236

**Comment by DevenRathod2** [comment]
can you please check my project please?

**Comment by xiaolin** [comment]
Sorry, I can't do that.

**Comment by DevenRathod2** [comment]
any other solution on this issue?

**Comment by Afsal102** [comment]
@DevenRathod2 assuming u might be in the latest react version and u are using app router, when u use this component you would need to mark your file with "use client" as currently u wont be able to render this on the server side since it contains interaction

**Comment by graphee-gabriel** [comment]
I have the same error, all work fine on local dev, but if I build and release I get:
```
image-gallery.js:1202 Uncaught TypeError: Super expression must either be null or a function
```
My react version: `"react": "^16.3.1"`

**Comment by sonegobruno** [comment]
> @DevenRathod2supondo que você esteja na versão mais recente do react e esteja usando o roteador de aplicativo, ao usar este componente, você precisará marcar seu arquivo com "usar cliente", pois atualmente você não será capaz de renderizá-lo no lado do servidor, pois contém interação

This solved to me

**Comment by samzmann** [comment]
This seems to be an issue with server side rendering. If you're using NextJS, you can add `'use client'` at the top of a file that imports `ImageGallery` to ensure that this file will we rendered on the client. This solves the issue for me.

**Comment by DevenRathod2** [comment]
Hey @samzmann Thanks for the response. I'll try this and let you know if its working or not.

**Comment by DevenRathod2** [comment]
Hello! @samzmann i fixed this issue. by just update the react-script to latest version.
